# Generated by Django 4.1.7 on 2023-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValveParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flange_c', models.CharField(max_length=10)),
                ('flange_thck', models.CharField(max_length=10)),
                ('shield_c', models.CharField(max_length=10)),
                ('pipe_c', models.CharField(max_length=10)),
                ('valve_c', models.CharField(max_length=10)),
                ('valve_l', models.CharField(max_length=10)),
                ('gap_left', models.CharField(max_length=10)),
                ('gap_right', models.CharField(max_length=10)),
            ],
        ),
    ]
