# Generated by Django 4.1.7 on 2023-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_valveparams_x_offset_valveparams_y_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valveparams',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
